export const TEXT_TYPES = {
	TITLE: 'TITLE',
	SUBHEADER: 'SUBHEADER',
	QUOTE: 'QUOTE',
	LARGE_BODY: 'LARGE_BODY',
	BODY: 'BODY',
	SECONDARY_BODY: 'SECONDARY_BODY',
	PLACEHOLDER: 'PLACEHOLDER',
	BUTTON: 'BUTTON',
};
