export const BUTTON_TYPES = {
	PRIMARY: 'PRIMARY',
	PRIMARY_CIRCLE: 'PRIMARY_CIRCLE',
	SECONDARY: 'SECONDARY',
	SUCCESS: 'SUCCESS',
	DANGER: 'DANGER',
	WARNING: 'WARNING',
	INFO: 'INFO',
	DARK: 'DARK',
	LIGHT: 'LIGHT',
	LIGHT_CIRCLE: 'LIGHT_CIRCLE',
	LINK: 'LINK',
};

export const BUTTON_LAYOUTS = {
	DEFAULT: 'DEFAULT',
	OUTLINE: 'outline',
};

export const BUTTON_SIZES = {
	SMALL: 'small',
	MEDIUM: 'medium',
	LARGE: 'large',
};
