
const COLORS = {
	PRIMARY: '#3CE5AA',
	PRIMARY_MEDIUM: '#B7F8E2',
	PRIMARY_LIGHT: '#E4FCF4',
	SECONDARY: '#7F7F7F',
	GRAY: '#B4B4B4',
	GRAY_LIGHT: '#E4E4E4',
	WHITE: '#FFF',
	LIGHT: '#FAFAFA',
};

export default COLORS;
